In [1]:
library(H5weaver)
library(Seurat)
library(dplyr)
library(ggplot2)
library(cowplot)
library(stringr)
library(scRepertoire)

Loading required package: data.table

Warning message:
“package ‘data.table’ was built under R version 4.4.3”
Loading required package: Matrix

Loading required package: rhdf5


Attaching package: ‘H5weaver’


The following objects are masked from ‘package:rhdf5’:

    h5dump, h5ls


Loading required package: SeuratObject

Loading required package: sp


Attaching package: ‘SeuratObject’


The following objects are masked from ‘package:base’:

    intersect, t


Warning message:
“package ‘dplyr’ was built under R version 4.4.3”

Attaching package: ‘dplyr’


The following objects are masked from ‘package:data.table’:

    between, first, last


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Warning message:
“package ‘ggplot2’ was built under R version 4.4.3”
Warning message:
“package ‘stringr’ was built under R version 4.4.3”

# Download

In [2]:
hise::readFiles(list("8b0d7e81-c9d9-48d1-a5fe-9aa1f7390030", "ebb65149-2a5b-494a-b1fd-f4aa17fc14e3", "ec8a395b-fb6b-41e7-9c21-60946210ef9e", "f276a473-7834-4c8e-b80b-344e2b30b677", "5a5babd2-2614-4f84-9371-9092dcb6b97c", "b967d76e-3acd-41a1-a9c6-e0ae62801c98", "6ec862f1-5c5d-44af-a3af-f671c040d6d8", "751eb5a6-7193-4cbd-9a9d-287a59ff4dc1", "0bb6162a-a1b4-49d7-885c-4545838bfab8", "c792a7a9-2340-4e04-a147-5e0f71de513e", "6233758d-984f-4785-9cd4-13e53da38b82", "dcc72042-d003-4244-b530-97b950e42eef", "a371bdc7-c241-4f9d-8b98-e969ac6d4ef7", "09db6716-bf3c-4c3d-bcfd-721ab8dee7e6", "5c247a60-3097-46d4-ac32-3b5be71ebf35", "e245f06d-b34c-4e7d-9480-0dca5d32a0f6", "5229aff3-3ca7-4867-8c13-39887ed81f9a", "0292d799-def3-4f00-9d60-5927497d1fbf", "aa978608-230f-4d0b-90e6-8b97d6d46c03", "371d2bb3-1045-4f46-9f35-4ff9e9772617", "08f3b8d7-f56a-4efe-9bb3-16db0bdce775", "3f85af31-9119-4178-bc57-787fa5d9a793", "4e115c59-acc8-48b0-b99b-3c65054c77e8", "90db99f2-90a6-4d0d-8138-9a4d074069f0", "1163ec5f-dc12-4f56-813c-37fbc2b80bdd", "e64252a7-ac4a-4308-b0ff-8929e9d10f69", "32ab4b2c-0511-4526-81d4-e3fed4d83382", "56f78b6e-e8a6-4ec3-86d0-8738c5141488", "09a4d3ee-0763-4e36-a757-270c9bcf6606", "f07966df-8f1b-4586-b836-4382d8ee7714", "ce4c3707-3534-4c58-8ed6-cd32cf5146bc", "8dd7c74a-8408-4f19-b250-5172f8894747", "cf9a2e6b-14ca-4c26-a110-3ba44811c87b", "1b211975-348a-42b3-8a82-a580169b63b6", "d1e442ca-0c1b-420c-80a6-b380a8d05189", "bbadf271-82e4-4d8b-9c97-87e79a415b93", "76a59cce-1161-445c-97e1-fdee50e0a39a", "c075f16d-1c44-4a76-8d4a-31a5f9ad148c", "19261324-2250-40b8-9002-eb57eea7bbec", "369cb9a7-abdc-4da7-af5d-e41efa2da464", "c70fea1e-4e72-4a08-96a7-1d27d34bdd33", "87f2fe3f-4679-4120-a846-1fb726478cb0", "b5b19497-690e-48aa-8ede-1ae8b3217172", "3a365216-b0dc-40cb-b710-2ab10c1b39c5", "f40e2a12-fb37-4ce4-b133-b55363ce9b39", "b5cdd2c3-ea60-420a-ad82-2d465dcc2927", "49098f37-2a6a-4d01-99b5-a80ea9992c31", "9148af04-7396-4c07-94a9-668e102c8ccf", "3cdae35d-0fed-4f28-8159-2d9730c1fd71", "f8e609cb-cce2-4ede-84b3-0592c350e5d9", "3b458412-656b-4913-8b63-727fd5270d12", "2f27e661-436b-4f6d-a9f6-81de96b21802", "3b425095-26ef-4696-8449-88a14c8664c7", "ec53c77b-5dbc-4c28-8c1f-e2a2c146d75a", "e03e756e-4471-4d16-93a0-99e0b79e72e2", "f04fc9e9-4835-4167-a513-3cedc02602b3", "7ede944d-e90c-4c97-9d5a-fa338cdac799", "a4dbeae2-ff66-450e-bfc8-ea65ba85eff7", "38c3a8d1-b91c-4e9d-a18c-c1cc029efd06", "d605de88-fa48-4d81-8adb-e03a7db3c8db", "2e26d972-be30-4eba-90d9-796fcf29aa15"))

In [3]:
h5_files <- list.files(path = '../../input/', pattern = 'celltypist.h5', recursive = TRUE, full.names = TRUE)
length(h5_files)

[1] 61

In [4]:
dex_list <- c('FIX10434-049','FIX10434-050','FIX10434-051','FIX10434-052',
              'FIX10434-053','FIX10434-054','FIX10434-055','FIX10434-056',
              'FIX10435-071','FIX10435-072','FIX10435-073','FIX10435-074',
              'FIX10435-075','FIX10435-076','FIX10435-077','FIX10435-078')

In [5]:
dex_list_match <- paste0('EXP-01589_',dex_list,'_celltypist.h5')

In [6]:
h5_trim <- h5_files[basename(h5_files) %in% dex_list_match]
length(h5_trim)

[1] 16

# Build

In [7]:
build_so_func <- function(h5_path){
    h5_list <- h5dump(h5_path)
    rna_mtx <- h5_list_convert_to_dgCMatrix(h5_list, target = 'matrix', feature_names = 'name')
    adt_mtx <- h5_list_convert_to_dgCMatrix(h5_list, target = 'ADT', feature_names = 'name')
    cell_meta <- read_h5_cell_meta(h5_path)

    so <- CreateSeuratObject(counts = rna_mtx$matrix_dgCMatrix, meta.data = cell_meta)
    so[['ADT']] <- CreateAssayObject(counts = adt_mtx$ADT_dgCMatrix)
    return(so)
}

In [8]:
so_list <- lapply(h5_trim, build_so_func)

Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”

In [9]:
so <- Reduce(merge, so_list)

In [10]:
so

An object of class Seurat
18144 features across 336847 samples within 2 assays
Active assay: RNA (18129 features, 0 variable features)
 16 layers present: counts.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1, counts.2, counts.2.1, counts.2.1.1, counts.2.1.1.1, counts.2.1.1.1.1, counts.2.1.1.1.1.1, counts.2.1.1.1.1.1.1, counts.2.1.1.1.1.1.1.1, counts.2.1.1.1.1.1.1.1.1, counts.2.1.1.1.1.1.1.1.1.1, counts.2.1.1.1.1.1.1.1.1.1.1, counts.2.1.1.1.1.1.1.1.1.1.1.1, counts.2.1.1.1.1.1.1.1.1.1.1.1.1, counts.2.1.1.1.1.1.1.1.1.1.1.1.1.1, counts.2.1.1.1.1.1.1.1.1.1.1.1.1.1.1
 1 other assay present: ADT

In [11]:
head(so@meta.data)

                                 orig.ident    nCount_RNA nFeature_RNA
73f40be29e3211f0be4eceafa7e98ddf SeuratProject 25493      6321
73f40caa9e3211f0be4eceafa7e98ddf SeuratProject  3057      1580
73f40d409e3211f0be4eceafa7e98ddf SeuratProject  8735      3825
73f40dc29e3211f0be4eceafa7e98ddf SeuratProject  2046      1356
73f40e4e9e3211f0be4eceafa7e98ddf SeuratProject  1004       665
73f40ec69e3211f0be4eceafa7e98ddf SeuratProject  9410      4062
                                 barcodes                         batch_id
73f40be29e3211f0be4eceafa7e98ddf 73f40be29e3211f0be4eceafa7e98ddf EXP-01589-PE
73f40caa9e3211f0be4eceafa7e98ddf 73f40caa9e3211f0be4eceafa7e98ddf EXP-01589-PE
73f40d409e3211f0be4eceafa7e98ddf 73f40d409e3211f0be4eceafa7e98ddf EXP-01589-PE
73f40dc29e3211f0be4eceafa7e98ddf 73f40dc29e3211f0be4eceafa7e98ddf EXP-01589-PE
73f40e4e9e3211f0be4eceafa7e98ddf 73f40e4e9e3211f0be4eceafa7e98ddf EXP-01589-PE
73f40ec69e3211f0be4eceafa7e98ddf 73f40ec69e3211f0be4eceafa7e98ddf EXP-01589-PE
                                 cell_name
73f40be29e3211f0be4eceafa7e98ddf unhonoured_weak_gannet
73f40caa9e3211f0be4eceafa7e98ddf newrich_mahogany_cusimanse
73f40d409e3211f0be4eceafa7e98ddf churchy_bigheaded_pitbull
73f40dc29e3211f0be4eceafa7e98ddf successive_brisk_whelp
73f40e4e9e3211f0be4eceafa7e98ddf climactic_inorganic_myna
73f40ec69e3211f0be4eceafa7e98ddf caressive_immobile_sturgeon
                                 cell_uuid
73f40be29e3211f0be4eceafa7e98ddf 73f40be29e3211f0be4eceafa7e98ddf
73f40caa9e3211f0be4eceafa7e98ddf 73f40caa9e3211f0be4eceafa7e98ddf
73f40d409e3211f0be4eceafa7e98ddf 73f40d409e3211f0be4eceafa7e98ddf
73f40dc29e3211f0be4eceafa7e98ddf 73f40dc29e3211f0be4eceafa7e98ddf
73f40e4e9e3211f0be4eceafa7e98ddf 73f40e4e9e3211f0be4eceafa7e98ddf
73f40ec69e3211f0be4eceafa7e98ddf 73f40ec69e3211f0be4eceafa7e98ddf
                                 chip_id        n_genes n_reads ⋯ probe_barcode
73f40be29e3211f0be4eceafa7e98ddf EXP-01589-PEC1 6321    82327   ⋯ BC008
73f40caa9e3211f0be4eceafa7e98ddf EXP-01589-PEC1 1580    11802   ⋯ BC008
73f40d409e3211f0be4eceafa7e98ddf EXP-01589-PEC1 3825    26324   ⋯ BC008
73f40dc29e3211f0be4eceafa7e98ddf EXP-01589-PEC1 1356     7786   ⋯ BC008
73f40e4e9e3211f0be4eceafa7e98ddf EXP-01589-PEC1  665     4082   ⋯ BC008
73f40ec69e3211f0be4eceafa7e98ddf EXP-01589-PEC1 4062    29115   ⋯ BC008
                                 sample_id    scrublet_call scrublet_score
73f40be29e3211f0be4eceafa7e98ddf FIX10435-078 0             0.38554217
73f40caa9e3211f0be4eceafa7e98ddf FIX10435-078 0             0.03015682
73f40d409e3211f0be4eceafa7e98ddf FIX10435-078 0             0.02040816
73f40dc29e3211f0be4eceafa7e98ddf FIX10435-078 0             0.01672926
73f40e4e9e3211f0be4eceafa7e98ddf FIX10435-078 0             0.01761658
73f40ec69e3211f0be4eceafa7e98ddf FIX10435-078 0             0.17241379
                                 well_id          nCount_ADT nFeature_ADT
73f40be29e3211f0be4eceafa7e98ddf EXP-01589-PEC1W1 9870       9
73f40caa9e3211f0be4eceafa7e98ddf EXP-01589-PEC1W1 2650       9
73f40d409e3211f0be4eceafa7e98ddf EXP-01589-PEC1W1 2283       9
73f40dc29e3211f0be4eceafa7e98ddf EXP-01589-PEC1W1 1579       9
73f40e4e9e3211f0be4eceafa7e98ddf EXP-01589-PEC1W1 1042       9
73f40ec69e3211f0be4eceafa7e98ddf EXP-01589-PEC1W1 2853       9
                                 AIFI_PBMC.Flex_L1 AIFI_PBMC.Flex_L2
73f40be29e3211f0be4eceafa7e98ddf NA                NA
73f40caa9e3211f0be4eceafa7e98ddf NA                NA
73f40d409e3211f0be4eceafa7e98ddf NA                NA
73f40dc29e3211f0be4eceafa7e98ddf NA                NA
73f40e4e9e3211f0be4eceafa7e98ddf NA                NA
73f40ec69e3211f0be4eceafa7e98ddf NA                NA
                                 AIFI_PBMC.Flex_L3
73f40be29e3211f0be4eceafa7e98ddf NA
73f40caa9e3211f0be4eceafa7e98ddf NA
73f40d409e3211f0be4eceafa7e98ddf NA
73f40dc29e3211f0be4eceafa7e98ddf NA
73f40e4e9e3211f0be4eceafa7e98ddf NA
73f40ec69e3211f0be4eceafa7e98ddf NA

In [12]:
table(so$pool_id)
table(so$well_id)

EXP-01589-PE EXP-01589-PF
      161699       175148

EXP-01589-PEC1W1 EXP-01589-PFC1W2
          161699           175148

# Add Metadata Information

In [13]:
meta <- read.csv('EXP-1589-DEX_metadata.csv')
head(meta)

  SampleID     BatchID   ProbeBarcodeID PoolID
1 FIX10435-071 EXP-01589 BC001          PE
2 FIX10435-075 EXP-01589 BC002          PE
3 FIX10435-072 EXP-01589 BC003          PE
4 FIX10435-076 EXP-01589 BC004          PE
5 FIX10435-073 EXP-01589 BC005          PE
6 FIX10435-077 EXP-01589 BC006          PE
  Condition
1 10435~IL4/IL7 +pep~Day 10~pp65 pos~NLVPMVATV
2 10435~IL4/IL7 +pep~Day 10~pp65 pos~NLVPMVATV
3 10435~IL4/IL7 +pep~Day 10~neg ctrl~pool
4 10435~IL4/IL7 +pep~Day 10~neg ctrl~pool
5 10435~IL15/IL7 +pep~Day 10~pp65 pos~NLVPMVATV
6 10435~IL15/IL7 +pep~Day 10~pp65 pos~NLVPMVATV
  Cytokine                            Donor   Timepoint
1 Cytokine:IL4_IL7_Peptide_Addn:Pep+  KT10435 Day_10
2 Cytokine:IL4_IL7_Peptide_Addn:Pep+  KT10435 Day_10
3 Cytokine:IL4_IL7_Peptide_Addn:Pep+  KT10435 Day_10
4 Cytokine:IL4_IL7_Peptide_Addn:Pep+  KT10435 Day_10
5 Cytokine:IL15_IL7_Peptide_Addn:Pep+ KT10435 Day_10
6 Cytokine:IL15_IL7_Peptide_Addn:Pep+ KT10435 Day_10

In [14]:
meta$pool_id <- paste0('EXP-01589-',meta$PoolID)
meta$probe_barcode <- meta$ProbeBarcodeID
meta$sample_id <- meta$SampleID
head(meta)

  SampleID     BatchID   ProbeBarcodeID PoolID
1 FIX10435-071 EXP-01589 BC001          PE
2 FIX10435-075 EXP-01589 BC002          PE
3 FIX10435-072 EXP-01589 BC003          PE
4 FIX10435-076 EXP-01589 BC004          PE
5 FIX10435-073 EXP-01589 BC005          PE
6 FIX10435-077 EXP-01589 BC006          PE
  Condition
1 10435~IL4/IL7 +pep~Day 10~pp65 pos~NLVPMVATV
2 10435~IL4/IL7 +pep~Day 10~pp65 pos~NLVPMVATV
3 10435~IL4/IL7 +pep~Day 10~neg ctrl~pool
4 10435~IL4/IL7 +pep~Day 10~neg ctrl~pool
5 10435~IL15/IL7 +pep~Day 10~pp65 pos~NLVPMVATV
6 10435~IL15/IL7 +pep~Day 10~pp65 pos~NLVPMVATV
  Cytokine                            Donor   Timepoint pool_id
1 Cytokine:IL4_IL7_Peptide_Addn:Pep+  KT10435 Day_10    EXP-01589-PE
2 Cytokine:IL4_IL7_Peptide_Addn:Pep+  KT10435 Day_10    EXP-01589-PE
3 Cytokine:IL4_IL7_Peptide_Addn:Pep+  KT10435 Day_10    EXP-01589-PE
4 Cytokine:IL4_IL7_Peptide_Addn:Pep+  KT10435 Day_10    EXP-01589-PE
5 Cytokine:IL15_IL7_Peptide_Addn:Pep+ KT10435 Day_10    EXP-01589-PE
6 Cytokine:IL15_IL7_Peptide_Addn:Pep+ KT10435 Day_10    EXP-01589-PE
  probe_barcode sample_id
1 BC001         FIX10435-071
2 BC002         FIX10435-075
3 BC003         FIX10435-072
4 BC004         FIX10435-076
5 BC005         FIX10435-073
6 BC006         FIX10435-077

In [15]:
new_meta <- so@meta.data %>%
    left_join(meta, by = c('sample_id','pool_id','probe_barcode'))

In [16]:
table(so$barcodes == new_meta$barcodes)

  TRUE
336847

In [17]:
so$Donor <- new_meta$Donor
so$Condition <- new_meta$Condition
so$Cytokine <- new_meta$Cytokine
so$Timepoint <- new_meta$Timepoint

# Subset only dextramer stained samples

In [18]:
table(so$Condition)

     10434~IL15/IL7 +pep~Day 10~neg ctrl~pool
                                        43325
10434~IL15/IL7 +pep~Day 10~pp65 pos~NLVPMVATV
                                        44334
      10434~IL4/IL7 +pep~Day 10~neg ctrl~pool
                                        37696
 10434~IL4/IL7 +pep~Day 10~pp65 pos~NLVPMVATV
                                        40168
     10435~IL15/IL7 +pep~Day 10~neg ctrl~pool
                                        41031
10435~IL15/IL7 +pep~Day 10~pp65 pos~NLVPMVATV
                                        41213
      10435~IL4/IL7 +pep~Day 10~neg ctrl~pool
                                        44267
 10435~IL4/IL7 +pep~Day 10~pp65 pos~NLVPMVATV
                                        44813

In [19]:
dex_stained <- subset(so, Condition %in% c('10434~IL15/IL7 +pep~Day 10~pp65 pos~NLVPMVATV','10434~IL4/IL7 +pep~Day 10~pp65 pos~NLVPMVATV','10435~IL15/IL7 +pep~Day 10~pp65 pos~NLVPMVATV','10435~IL4/IL7 +pep~Day 10~pp65 pos~NLVPMVATV'))

In [20]:
dex_stained

An object of class Seurat
18144 features across 170528 samples within 2 assays
Active assay: RNA (18129 features, 0 variable features)
 8 layers present: counts.2, counts.2.1.1, counts.2.1.1.1, counts.2.1.1.1.1, counts.2.1.1.1.1.1, counts.2.1.1.1.1.1.1.1, counts.2.1.1.1.1.1.1.1.1, counts.2.1.1.1.1.1.1.1.1.1.1.1.1.1
 1 other assay present: ADT

In [21]:
table(is.na(dex_stained$AIFI_PBMC.Flex_L1))

 FALSE
170528

## Add TCR

In [22]:
add_tcr_func_sample <- function(seurat_object, pool){
    # build barcode dataframe
    barcodes_df <- select(seurat_object@meta.data, classic_barcodes, barcodes)

    # extract sample ID
    sample_id <- unique(seurat_object$sample_id)

    # subset T cells
    t_cells <- subset(seurat_object, AIFI_PBMC.Flex_L1 == 'T cell')
    non_t_cells <- subset(seurat_object, AIFI_PBMC.Flex_L1 != 'T cell')
    
    # load tcr
    tcr <- read.csv(paste0('tcr/',pool,'-clones/','EXP-1589-DEX-',pool,'.',sample_id,'.alignments.clones.tsv'),sep='\t')

    # replace barcodes with barcodes from pipeline
    tcr_updated <- tcr %>%
        left_join(barcodes_df, by = c("tagValueCELL" = "classic_barcodes")) %>%
        mutate(tagValueCELL = ifelse(!is.na(barcodes), barcodes, tagValueCELL)) %>%
        select(-barcodes)
    # trim barcodes for any non-TCR clones
    tcr_updated <- tcr_updated[!(tcr_updated$topChains %in% c("IGH", "IGK", "IGL")), ]
    # load via scRep
    tcr_contigs <- loadContigs(tcr_updated, format = 'MiXCR')
    combined.TCR <- combineTCR(tcr_contigs,
                               removeNA = FALSE, 
                               removeMulti = FALSE, 
                               filterMulti = TRUE)
    t_cells <- combineExpression(combined.TCR, 
                                 t_cells, 
                                 cloneCall="gene",
                                 proportion = TRUE)

    seurat_object <- merge(t_cells, non_t_cells)

    return(seurat_object)
}

In [23]:
add_tcr_func_batch <- function(seurat_object,pool){
    # split object by sample
    print("Splitting Object")
    flush.console()
    so_split <- SplitObject(seurat_object, split.by = 'sample_id')
    # loop through and add tcr info
    print("Adding TCR")
    flush.console()
    so_split <- lapply(so_split, function(x){
        x <- add_tcr_func_sample(x, pool)
        return(x)
    })
    print("Merging Object")
    flush.console()
    seurat_object <- Reduce(merge, so_split)    
    return(seurat_object)
}

In [24]:
dex_stained$classic_barcodes <- substr(dex_stained$original_barcodes, 1, nchar(dex_stained$original_barcodes)-8)

In [25]:
pool_split <- SplitObject(dex_stained, split.by = 'pool_id')

In [26]:
pool_split$`EXP-01589-PE` <- add_tcr_func_batch(seurat_object = pool_split$`EXP-01589-PE`, pool = 'PA')

[1] "Splitting Object"
[1] "Adding TCR"
[1] "Merging Object"

In [27]:
pool_split$`EXP-01589-PF` <- add_tcr_func_batch(seurat_object = pool_split$`EXP-01589-PF`, pool = 'PB')

[1] "Splitting Object"
[1] "Adding TCR"
[1] "Merging Object"

In [28]:
dex_tcr <- Reduce(merge, pool_split)

In [29]:
saveRDS(dex_tcr, 'dextramer_tcr.rds')

In [30]:
sessionInfo()

R version 4.4.1 (2024-06-14)
Platform: x86_64-conda-linux-gnu
Running under: Ubuntu 22.04.5 LTS

Matrix products: default
BLAS/LAPACK: /home/workspace/environment/minimal/lib/libopenblasp-r0.3.28.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=C.UTF-8    LC_NUMERIC=C        LC_TIME=C
 [4] LC_COLLATE=C        LC_MONETARY=C       LC_MESSAGES=C
 [7] LC_PAPER=C          LC_NAME=C           LC_ADDRESS=C
[10] LC_TELEPHONE=C      LC_MEASUREMENT=C    LC_IDENTIFICATION=C

time zone: America/Los_Angeles
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
 [1] scRepertoire_2.5.3 stringr_1.5.2      cowplot_1.2.0      ggplot2_4.0.0
 [5] dplyr_1.1.4        Seurat_5.3.0       SeuratObject_5.1.0 sp_2.2-0
 [9] H5weaver_1.3.0     rhdf5_2.50.2       Matrix_1.7-3       data.table_1.17.8

loaded via a namespace (and not attached):
  [1] RcppAnnoy_0.0.22            splines_4.4.1
  [3] later_1.4.2                 pbdZMQ_0.3-14
  [5] tibble_3.3.0                polyclip_1.10-7
  [7] fastDummies_1.7.5           lifecycle_1.0.4
  [9] globals_0.18.0              lattice_0.22-7
 [11] MASS_7.3-65                 magrittr_2.0.3
 [13] plotly_4.11.0               httpuv_1.6.16
 [15] sctransform_0.4.2           spam_2.11-1
 [17] spatstat.sparse_3.1-0       reticulate_1.43.0
 [19] pbapply_1.7-4               RColorBrewer_1.1-3
 [21] abind_1.4-8                 zlibbioc_1.52.0
 [23] rvest_1.0.4                 Rtsne_0.17
 [25] GenomicRanges_1.58.0        purrr_1.1.0
 [27] ggraph_2.2.1                BiocGenerics_0.52.0
 [29] hash_2.2.6.3                tweenr_2.0.3
 [31] evmix_2.12                  GenomeInfoDbData_1.2.13
 [33] IRanges_2.40.0              S4Vectors_0.44.0
 [35] ggrepel_0.9.6               irlba_2.3.5.1
 [37] listenv_0.9.1               spatstat.utils_3.1-5
 [39] iNEXT_3.0.1                 MatrixModels_0.5-4
 [41] goftest_1.2-3               RSpectra_0.16-2
 [43] spatstat.random_3.4-1       fitdistrplus_1.2-4
 [45] parallelly_1.45.0           codetools_0.2-20
 [47] DelayedArray_0.32.0         xml2_1.3.8
 [49] ggforce_0.5.0               tidyselect_1.2.1
 [51] UCSC.utils_1.2.0            farver_2.1.2
 [53] viridis_0.6.5               matrixStats_1.5.0
 [55] stats4_4.4.1                base64enc_0.1-3
 [57] spatstat.explore_3.4-3      jsonlite_2.0.0
 [59] tidygraph_1.3.1             progressr_0.15.1
 [61] ggridges_0.5.6              ggalluvial_0.12.5
 [63] survival_3.8-3              systemfonts_1.2.3
 [65] tools_4.4.1                 ragg_1.3.3
 [67] ica_1.0-3                   Rcpp_1.1.0
 [69] glue_1.8.0                  gridExtra_2.3
 [71] SparseArray_1.6.0           MatrixGenerics_1.18.0
 [73] GenomeInfoDb_1.42.0         IRdisplay_1.1
 [75] withr_3.0.2                 fastmap_1.2.0
 [77] rhdf5filters_1.18.1         SparseM_1.84-2
 [79] digest_0.6.37               R6_2.6.1
 [81] mime_0.13                   textshaping_0.4.0
 [83] scattermore_1.2             tensor_1.5.1
 [85] spatstat.data_3.1-6         tidyr_1.3.1
 [87] generics_0.1.4              graphlayouts_1.2.2
 [89] httr_1.4.7                  htmlwidgets_1.6.4
 [91] S4Arrays_1.6.0              uwot_0.2.3
 [93] pkgconfig_2.0.3             gtable_0.3.6
 [95] lmtest_0.9-40               S7_0.2.0
 [97] SingleCellExperiment_1.28.0 XVector_0.46.0
 [99] htmltools_0.5.8.1           dotCall64_1.2
[101] scales_1.4.0                Biobase_2.66.0
[103] png_0.1-8                   spatstat.univar_3.1-4
[105] ggdendro_0.2.0              rjson_0.2.23
[107] reshape2_1.4.4              uuid_1.2-1
[109] nlme_3.1-168                repr_1.1.7
[111] zoo_1.8-14                  cachem_1.1.0
[113] KernSmooth_2.23-26          parallel_4.4.1
[115] miniUI_0.1.2                pillar_1.11.0
[117] grid_4.4.1                  vctrs_0.6.5
[119] RANN_2.6.2                  promises_1.3.3
[121] xtable_1.8-4                cluster_2.1.8.1
[123] evaluate_1.0.4              cli_3.6.5
[125] compiler_4.4.1              rlang_1.1.6
[127] crayon_1.5.3                future.apply_1.20.0
[129] immApex_1.3.6               plyr_1.8.9
[131] stringi_1.8.7               viridisLite_0.4.2
[133] deldir_2.0-4                assertthat_0.2.1
[135] gsl_2.1-8                   lazyeval_0.2.2
[137] spatstat.geom_3.5-0         quantreg_6.1
[139] IRkernel_1.3.2              RcppHNSW_0.6.0
[141] patchwork_1.3.1             future_1.58.0
[143] Rhdf5lib_1.28.0             shiny_1.11.1
[145] SummarizedExperiment_1.36.0 ROCR_1.0-11
[147] igraph_2.1.4                memoise_2.0.1